language: go
go:
  - 1.9.x
#  - release
#  - tip


services:
  - docker

addons:
  apt:
    packages:
    - rpm

matrix:
#  allow_failures:
#    - go: release
#    - go: tip
  fast_finish: true


cache:
  pip: true

before_install:
  - make before_install

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh

script:
  - make vet
  - make script

after_failure:
  - make after_failure

after_success:
  - make after_success

deploy:
  # We do a `skip_cleanup` because when the docker-compose runs, it creates files in the host file system with the
  # userid `1000`. Our travis user does not have the userid `1000`, so it can not clean those files up, causing the
  # deploy to break.
  - provider: script
    script: make deploy_on_tag
    on:
      tags: true
      condition: $TRAVIS_GO_VERSION =~ ^1\.9(\.[0-9]+)?$
  - provider: script
    script: make deploy_on_develop
    on:
      branch: develop